In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import scipy.stats as stats

In [2]:
# Read in .csv dataset, 1999

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_1999.csv'
CVD_1999_df = pd.read_csv(path)
CVD_1999_df["year"] = CVD_1999_df["year"].astype(float)
CVD_1999_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [3]:
# Read in .csv dataset, 2000

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2000.csv'
CVD_2000_df = pd.read_csv(path)
CVD_2000_df["year"] = CVD_2000_df["year"].astype(float)
CVD_2000_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [4]:
# Read in .csv dataset, 2001

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2001.csv'
CVD_2001_df = pd.read_csv(path)
CVD_2001_df["year"] = CVD_2001_df["year"].astype(float)
CVD_2001_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [5]:
# Read in .csv dataset, 2002

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2002.csv'
CVD_2002_df = pd.read_csv(path)
CVD_2002_df["year"] = CVD_2002_df["year"].astype(float)
CVD_2002_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [8]:
# Read in .csv dataset, 2003

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2003.csv'
CVD_2003_df = pd.read_csv(path)
CVD_2003_df["year"] = CVD_2003_df["year"].astype(float)
CVD_2003_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [9]:
# Read in .csv dataset, 2004

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2004.csv'
CVD_2004_df = pd.read_csv(path)
CVD_2004_df["year"] = CVD_2004_df["year"].astype(float)
CVD_2004_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  147995 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102885 non-null  object
 11  data_value_footnote         102885 non-null  object
 12  confidence_limit_low        147995 non-null  float64
 13  confidence_limit_high       147995 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [10]:
# Read in .csv dataset, 2005

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2005.csv'
CVD_2005_df = pd.read_csv(path)
CVD_2005_df["year"] = CVD_2005_df["year"].astype(float)
CVD_2005_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [11]:
# Read in .csv dataset, 2006

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2006.csv'
CVD_2006_df = pd.read_csv(path)
CVD_2006_df["year"] = CVD_2006_df["year"].astype(float)
CVD_2006_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [12]:
# Read in .csv dataset, 2007

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2007.csv'
CVD_2007_df = pd.read_csv(path)
CVD_2007_df["year"] = CVD_2007_df["year"].astype(float)
CVD_2007_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [13]:
# Read in .csv dataset, 2008

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2008.csv'
CVD_2008_df = pd.read_csv(path)
CVD_2008_df["year"] = CVD_2008_df["year"].astype(float)
CVD_2008_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [14]:
# Read in .csv dataset, 2009

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2009.csv'
CVD_2009_df = pd.read_csv(path)
CVD_2009_df["year"] = CVD_2009_df["year"].astype(float)
CVD_2009_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [15]:
# Read in .csv dataset, 2010

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2010.csv'
CVD_2010_df = pd.read_csv(path)
CVD_2010_df["year"] = CVD_2010_df["year"].astype(float)
CVD_2010_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [16]:
# Read in .csv dataset, 2011

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2011.csv'
CVD_2011_df = pd.read_csv(path)
CVD_2011_df["year"] = CVD_2011_df["year"].astype(float)
CVD_2011_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [17]:
# Read in .csv dataset, 2012

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2012.csv'
CVD_2012_df = pd.read_csv(path)
CVD_2012_df["year"] = CVD_2012_df["year"].astype(float)
CVD_2012_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [18]:
# Read in .csv dataset, 2013

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2013.csv'
CVD_2013_df = pd.read_csv(path)
CVD_2013_df["year"] = CVD_2013_df["year"].astype(float)
CVD_2013_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [19]:
# Read in .csv dataset, 2014

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2014.csv'
CVD_2014_df = pd.read_csv(path)
CVD_2014_df["year"] = CVD_2014_df["year"].astype(float)
CVD_2014_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [20]:
# Read in .csv dataset, 2015

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2015.csv'
CVD_2015_df = pd.read_csv(path)
CVD_2015_df["year"] = CVD_2015_df["year"].astype(float)
CVD_2015_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [21]:
# Read in .csv dataset, 2016

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2016.csv'
CVD_2016_df = pd.read_csv(path)
CVD_2016_df["year"] = CVD_2016_df["year"].astype(float)
CVD_2016_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [22]:
# Read in .csv dataset, 2017

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2017.csv'
CVD_2017_df = pd.read_csv(path)
CVD_2017_df["year"] = CVD_2017_df["year"].astype(float)
CVD_2017_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [23]:
# Read in .csv dataset, 2018

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2018.csv'
CVD_2018_df = pd.read_csv(path)
CVD_2018_df["year"] = CVD_2018_df["year"].astype(float)
CVD_2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [24]:
# Read in .csv dataset, 2019

path = 'Resources/CDC_Rates_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults_By_State_Race_Ethnicity_and_Sex_2019.csv'
CVD_2019_df = pd.read_csv(path)
CVD_2019_df["year"] = CVD_2019_df["year"].astype(float)
CVD_2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250880 entries, 0 to 250879
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   year                        250880 non-null  float64
 1   locationabbr                250880 non-null  object
 2   locationdesc                250880 non-null  object
 3   geographiclevel             250880 non-null  object
 4   datasource                  250880 non-null  object
 5   class                       250880 non-null  object
 6   topic                       250880 non-null  object
 7   data_value                  148050 non-null  float64
 8   data_value_unit             250880 non-null  object
 9   data_value_type             250880 non-null  object
 10  data_value_footnote_symbol  102830 non-null  object
 11  data_value_footnote         102830 non-null  object
 12  confidence_limit_low        148050 non-null  float64
 13  confidence_limit_high       148050 non-null  float64
 14  stratificationcategory1     250880 non-null  object
 15  stratification1             250880 non-null  object
 16  stratificationcategory2     250880 non-null  object
 17  stratification2             250880 non-null  object
 18  stratificationcategory3     250880 non-null  object
 19  stratification3             250880 non-null  object
 20  locationid                  250880 non-null  int64
dtypes: float64(4), int64(1), object(16)
memory usage: 40.2+ MB

In [27]:
# Drop rows with NA values in the 'data_value' column, 1999
Clean_CVD_1999_df = CVD_1999_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_1999_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,155.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,126.0,182.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,26.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.2,33.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),98.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,78.7,132.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),192.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,165.0,239.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,27.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.8,45.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [28]:
# Drop rows with NA values in the 'data_value' column, 2000
Clean_CVD_2000_df = CVD_2000_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2000_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,160.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,131.7,188.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.2,32.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),97.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,77.9,127.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),192.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,162.6,233.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,28.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.9,43.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [29]:
# Drop rows with NA values in the 'data_value' column, 2001
Clean_CVD_2001_df = CVD_2001_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2001_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,153.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,130.2,184.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.7,31.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),89.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,72.8,109.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),186.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,160.2,218.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,32.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,23.5,50.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [30]:
# Drop rows with NA values in the 'data_value' column, 2002
Clean_CVD_2002_df = CVD_2002_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2002_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,151.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,126.5,177.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.2,32.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),80.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,65.4,99.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),188.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,164.1,213.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,35.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,27.0,47.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [31]:
# Drop rows with NA values in the 'data_value' column, 2003
Clean_CVD_2003_df = CVD_2003_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2003_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,159.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,137.4,189.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.7,31.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),68.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,59.8,82.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),194.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,173.1,220.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,46.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,35.9,62.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [32]:
# Drop rows with NA values in the 'data_value' column, 2004
Clean_CVD_2004_df = CVD_2004_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2004_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,163.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,142.4,189.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.0,31.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),67.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.9,82.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),196.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,168.3,222.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,57.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,45.1,72.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [33]:
# Drop rows with NA values in the 'data_value' column, 2005
Clean_CVD_2005_df = CVD_2005_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2005_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,168.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.5,195.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.9,32.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),66.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.7,82.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),205.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,176.0,233.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,72.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,59.1,94.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [34]:
# Drop rows with NA values in the 'data_value' column, 2006
Clean_CVD_2006_df = CVD_2006_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2006_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,164.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,142.5,194.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.1,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),63.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,50.2,79.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),194.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,171.1,218.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,65.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.5,80.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [35]:
# Drop rows with NA values in the 'data_value' column, 2007
Clean_CVD_2007_df = CVD_2007_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2007_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,148.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,130.2,170.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.8,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),54.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.0,70.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,161.7,206.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,60.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,48.4,75.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [36]:
# Drop rows with NA values in the 'data_value' column, 2008
Clean_CVD_2008_df = CVD_2008_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2008_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,151.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,133.5,169.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,29.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,45.8,72.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),184.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,163.3,206.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,58.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,43.3,70.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [37]:
# Drop rows with NA values in the 'data_value' column, 2009
Clean_CVD_2009_df = CVD_2009_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2009_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,153.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,133.1,174.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.0,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.6,69.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,156.5,204.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,57.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,42.4,71.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [38]:
# Drop rows with NA values in the 'data_value' column, 2010
Clean_CVD_2010_df = CVD_2010_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2010_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,148.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,129.0,174.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,29.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.9,69.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,155.8,204.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,44.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,30.8,55.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [39]:
# Drop rows with NA values in the 'data_value' column, 2011
Clean_CVD_2011_df = CVD_2011_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2011_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
4,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,29.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.9,39.7,Age group,Ages 35-64 years,Race,Overall,Sex,Men,1001
6,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,146.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,127.3,168.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.0,28.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.8,71.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),182.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,155.6,211.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [40]:
# Drop rows with NA values in the 'data_value' column, 2012
Clean_CVD_2012_df = CVD_2012_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2012_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,140.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,121.2,162.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.3,30.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),59.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,47.6,74.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),175.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,149.5,197.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,24.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.6,32.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [41]:
# Drop rows with NA values in the 'data_value' column, 2013
Clean_CVD_2013_df = CVD_2013_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2013_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,144.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,124.9,166.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.3,28.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),72.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,60.3,85.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),183.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,158.4,208.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,27.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.2,34.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [42]:
# Drop rows with NA values in the 'data_value' column, 2014
Clean_CVD_2014_df = CVD_2014_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2014_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,131.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.6,152.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.4,28.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),74.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,63.1,90.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),171.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,149.6,194.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,25.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.4,32.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [43]:
# Drop rows with NA values in the 'data_value' column, 2015
Clean_CVD_2015_df = CVD_2015_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2015_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.1,150.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.2,31.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),73.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,62.5,90.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),168.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,147.2,185.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,30.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [44]:
# Drop rows with NA values in the 'data_value' column, 2016
Clean_CVD_2016_df = CVD_2016_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2016_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
3,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.3,30.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,114.1,145.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),78.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,65.7,91.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),164.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.7,184.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,21.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,17.7,27.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [45]:
# Drop rows with NA values in the 'data_value' column, 2017
Clean_CVD_2017_df = CVD_2017_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2017_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,33.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,25.4,44.1,Age group,Ages 35-64 years,Race,Overall,Sex,Men,1001
6,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.1,144.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.4,29.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),84.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,72.5,98.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),162.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,143.8,182.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [47]:
# Drop rows with NA values in the 'data_value' column, 2018
Clean_CVD_2018_df = CVD_2018_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2018_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,126.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,109.0,145.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,27.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.9,33.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),80.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,66.9,95.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),162.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.3,181.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.9,28.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [48]:
# Drop rows with NA values in the 'data_value' column, 2019
Clean_CVD_2019_df = CVD_2019_df.dropna(subset=['data_value'])

# Display the first few rows of the cleaned DataFrame
Clean_CVD_2019_df.head()

,year,locationabbr,locationdesc,geographiclevel,datasource,class,topic,data_value,data_value_unit,data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,stratification1,stratificationcategory2,stratification2,stratificationcategory3,stratification3,locationid
5,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,122.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,106.4,143.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,28.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.7,34.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),70.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,57.9,87.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),158.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,137.4,181.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.5,29.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [76]:
# Rename original columns, 1999
Renamed_CVD_1999_df = Clean_CVD_1999_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_1999_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,155.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,126.0,182.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,26.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.2,33.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),98.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,78.7,132.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),192.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,165.0,239.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,1999.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,27.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.8,45.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [77]:
# Rename original columns, 2000
Renamed_CVD_2000_df = Clean_CVD_2000_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2000_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,160.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,131.7,188.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.2,32.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),97.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,77.9,127.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),192.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,162.6,233.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2000.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,28.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.9,43.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [78]:
# Rename original columns, 2001
Renamed_CVD_2001_df = Clean_CVD_2001_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2001_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,153.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,130.2,184.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.7,31.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),89.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,72.8,109.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),186.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,160.2,218.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2001.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,32.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,23.5,50.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [79]:
# Rename original columns, 2002
Renamed_CVD_2002_df = Clean_CVD_2002_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2002_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,151.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,126.5,177.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.2,32.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),80.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,65.4,99.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),188.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,164.1,213.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2002.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,35.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,27.0,47.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [80]:
# Rename original columns, 2003
Renamed_CVD_2003_df = Clean_CVD_2003_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2003_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,159.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,137.4,189.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.7,31.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),68.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,59.8,82.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),194.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,173.1,220.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2003.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,46.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,35.9,62.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [81]:
# Rename original columns, 2004
Renamed_CVD_2004_df = Clean_CVD_2004_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2004_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,163.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,142.4,189.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.0,31.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),67.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.9,82.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),196.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,168.3,222.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2004.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,57.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,45.1,72.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [82]:
# Rename original columns, 2005
Renamed_CVD_2005_df = Clean_CVD_2005_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2005_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,168.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.5,195.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.9,32.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),66.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.7,82.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),205.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,176.0,233.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2005.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,72.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,59.1,94.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [83]:
# Rename original columns, 2006
Renamed_CVD_2006_df = Clean_CVD_2006_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2006_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,164.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,142.5,194.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.1,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),63.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,50.2,79.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),194.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,171.1,218.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2006.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,65.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,53.5,80.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [84]:
# Rename original columns, 2007
Renamed_CVD_2007_df = Clean_CVD_2007_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2007_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,148.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,130.2,170.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.8,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),54.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.0,70.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,161.7,206.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2007.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,60.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,48.4,75.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [85]:
# Rename original columns, 2008
Renamed_CVD_2008_df = Clean_CVD_2008_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2008_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,151.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,133.5,169.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,29.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,45.8,72.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),184.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,163.3,206.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2008.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,58.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,43.3,70.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [86]:
# Rename original columns, 2009
Renamed_CVD_2009_df = Clean_CVD_2009_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2009_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,153.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,133.1,174.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.0,30.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.6,69.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,156.5,204.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2009.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,57.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,42.4,71.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [87]:
# Rename original columns, 2010
Renamed_CVD_2010_df = Clean_CVD_2010_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2010_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,148.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,129.0,174.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,29.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.9,69.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),181.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,155.8,204.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2010.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,44.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,30.8,55.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [88]:
# Rename original columns, 2011
Renamed_CVD_2011_df = Clean_CVD_2011_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2011_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
4,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,29.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.9,39.7,Age group,Ages 35-64 years,Race,Overall,Sex,Men,1001
6,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,146.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,127.3,168.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.0,28.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),56.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,46.8,71.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2011.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),182.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,155.6,211.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [89]:
# Rename original columns, 2012
Renamed_CVD_2012_df = Clean_CVD_2012_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2012_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,140.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,121.2,162.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.3,30.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),59.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,47.6,74.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),175.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,149.5,197.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2012.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,24.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.6,32.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [90]:
# Rename original columns, 2013
Renamed_CVD_2013_df = Clean_CVD_2013_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2013_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,144.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,124.9,166.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.3,28.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),72.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,60.3,85.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),183.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,158.4,208.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2013.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,27.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,20.2,34.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [91]:
# Rename original columns, 2014
Renamed_CVD_2014_df = Clean_CVD_2014_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2014_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,131.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.6,152.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,24.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.4,28.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),74.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,63.1,90.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),171.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,149.6,194.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2014.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,25.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,19.4,32.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [92]:
# Rename original columns, 2015
Renamed_CVD_2015_df = Clean_CVD_2015_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2015_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.1,150.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.2,31.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),73.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,62.5,90.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),168.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,147.2,185.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2015.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.6,30.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [93]:
# Rename original columns, 2016
Renamed_CVD_2016_df = Clean_CVD_2016_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2016_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
3,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.3,30.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,114.1,145.5,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),78.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,65.7,91.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),164.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.7,184.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2016.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,21.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,17.7,27.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [94]:
# Rename original columns, 2017
Renamed_CVD_2017_df = Clean_CVD_2017_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2017_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,33.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,25.4,44.1,Age group,Ages 35-64 years,Race,Overall,Sex,Men,1001
6,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,128.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,113.1,144.7,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,25.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,21.4,29.6,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),84.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,72.5,98.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2017.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),162.8,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,143.8,182.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [95]:
# Rename original columns, 2018
Renamed_CVD_2018_df = Clean_CVD_2018_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2018_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,126.5,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,109.0,145.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,27.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.9,33.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),80.1,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,66.9,95.1,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),162.4,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,145.3,181.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2018.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.9,28.3,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [96]:
# Rename original columns, 2019
Renamed_CVD_2019_df = Clean_CVD_2019_df.rename(columns = {"locationabbr": "US States", 
                                                    "locationdesc": "US County",
                                                    "topic": "CVD Type", 
                                                    "data_value_unit": "Rate per 100,000 population",
                                                    "stratification1": "Age range", 
                                                    "stratification2": "Ethnicity", 
                                                    "stratification3": "Gender"})
Renamed_CVD_2019_df.head()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
5,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All heart disease,122.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,106.4,143.4,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
6,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,All stroke,28.0,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,22.7,34.9,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
7,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),70.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,57.9,87.0,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
8,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),158.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,137.4,181.2,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001
9,2019.0,AL,Autauga,County,NVSS,Cardiovascular Diseases,Heart failure,23.9,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,18.5,29.8,Age group,Ages 35-64 years,Race,Overall,Sex,Overall,1001

In [100]:
# List of all the DataFrame names
dataframes = [
    Renamed_CVD_1999_df, Renamed_CVD_2000_df, Renamed_CVD_2001_df, Renamed_CVD_2002_df,
    Renamed_CVD_2003_df, Renamed_CVD_2004_df, Renamed_CVD_2005_df, Renamed_CVD_2006_df,
    Renamed_CVD_2007_df, Renamed_CVD_2008_df, Renamed_CVD_2009_df, Renamed_CVD_2010_df,
    Renamed_CVD_2011_df, Renamed_CVD_2012_df, Renamed_CVD_2013_df, Renamed_CVD_2014_df,
    Renamed_CVD_2015_df, Renamed_CVD_2016_df, Renamed_CVD_2017_df, Renamed_CVD_2018_df,
    Renamed_CVD_2019_df
]

# Concatenate all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Display the last few rows of the combined DataFrame to check append has worked
combined_df.tail()

,year,US States,US County,geographiclevel,datasource,class,CVD Type,data_value,"Rate per 100,000 population",data_value_type,...,data_value_footnote,confidence_limit_low,confidence_limit_high,stratificationcategory1,Age range,stratificationcategory2,Ethnicity,stratificationcategory3,Gender,locationid
3108715,2019.0,WY,Weston,County,NVSS,Cardiovascular Diseases,All heart disease,1004.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,869.1,1149.6,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
3108716,2019.0,WY,Weston,County,NVSS,Cardiovascular Diseases,All stroke,215.6,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,179.1,277.7,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
3108717,2019.0,WY,Weston,County,NVSS,Cardiovascular Diseases,Coronary heart disease (CHD),570.7,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,460.1,720.9,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
3108718,2019.0,WY,Weston,County,NVSS,Cardiovascular Diseases,Cardiovascular disease (CVD),1277.3,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,1150.1,1460.2,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045
3108719,2019.0,WY,Weston,County,NVSS,Cardiovascular Diseases,Heart failure,478.2,"per 100,000","Age-Standardized, Spatiotemporally Smoothed Rate",...,NaN,408.0,564.6,Age group,Ages 65 years and older,Race,White,Sex,Overall,56045

In [103]:
# Group by the specified columns and calculate the mean for 'Data_Value/100_000 People' by County
Averaged_grouped_df = combined_df.groupby(
    ['US States', 'year', 'Ethnicity', 'Gender', 'CVD Type', 'Age range'],
    as_index=False
)['data_value'].mean()

# Display the first few rows of the resulting DataFrame
Averaged_grouped_df.head()


# ^^ So basically it takes any rows that have the same values in columns 'US States', 
# 'Year' 'Ethnicity' , 'Gender', 'Heart Disease Type' and 'Age range'
# and finds the average of those rows then returns a data frame with
# one value (average) for the 'Data_Value/100_000 People'.

,US States,year,Ethnicity,Gender,CVD Type,Age range,data_value
0,AK,1999.0,American Indian/Alaska Native,Overall,All heart disease,Ages 35-64 years,84.886667
1,AK,1999.0,American Indian/Alaska Native,Overall,All heart disease,Ages 65 years and older,1433.755556
2,AK,1999.0,American Indian/Alaska Native,Overall,All stroke,Ages 35-64 years,23.786667
3,AK,1999.0,American Indian/Alaska Native,Overall,All stroke,Ages 65 years and older,680.877778
4,AK,1999.0,American Indian/Alaska Native,Overall,Cardiovascular disease (CVD),Ages 35-64 years,87.780000

In [109]:
# Filtered DF to check if above is correct:
# Filter the DataFrame

df = Averaged_grouped_df

filtered_df = df[
    (df['US States'] == 'AK') &
    (df['year'] == 1999.0) &
    (df['Ethnicity'] == 'American Indian/Alaska Native') &
    (df['Gender'] == 'Overall') &
    (df['CVD Type'] == 'All heart disease') &
    (df['Age range'] == 'Ages 65 years and older')
]

filtered_df

,US States,year,Ethnicity,Gender,CVD Type,Age range,data_value
1,AK,1999.0,American Indian/Alaska Native,Overall,All heart disease,Ages 65 years and older,1433.755556

In [110]:
# Rename columns to match original:
Averaged_grouped_df = Averaged_grouped_df.rename(columns = {"year": "Year", 
                                                    "CVD Type": "Heart Disease Type",
                                                    "data_value": "Data_Value/100_000 People"})
Averaged_grouped_df.head()

,US States,Year,Ethnicity,Gender,Heart Disease Type,Age range,Data_Value/100_000 People
0,AK,1999.0,American Indian/Alaska Native,Overall,All heart disease,Ages 35-64 years,84.886667
1,AK,1999.0,American Indian/Alaska Native,Overall,All heart disease,Ages 65 years and older,1433.755556
2,AK,1999.0,American Indian/Alaska Native,Overall,All stroke,Ages 35-64 years,23.786667
3,AK,1999.0,American Indian/Alaska Native,Overall,All stroke,Ages 65 years and older,680.877778
4,AK,1999.0,American Indian/Alaska Native,Overall,Cardiovascular disease (CVD),Ages 35-64 years,87.780000

In [112]:
# Show a list of all the different states in the dataset
state_list = Averaged_grouped_df['US States'].unique().tolist()
state_list

['AK',
 'AL',
 'AR',
 'AZ',
 'CA',
 'CO',
 'CT',
 'DC',
 'DE',
 'FL',
 'GA',
 'HI',
 'IA',
 'ID',
 'IL',
 'IN',
 'KS',
 'KY',
 'LA',
 'MA',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MS',
 'MT',
 'NC',
 'ND',
 'NE',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'UT',
 'VA',
 'VT',
 'WA',
 'WI',
 'WV',
 'WY']

In [114]:
Averaged_grouped_df.to_csv('Averaged_Cleaned_filtered_data.csv', index=False)